name = "MultiAssign"
uuid = "5e2c8b86-4afa-40de-bd09-d9d381e5dc2b"
authors = ["Mark Baum <markmbaum@protonmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
